backend:
  name: github
  branch: master

media_folder: "pics"
public_folder: "/pics"

collections:
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: textarea }
      - { name: price, label: Price, widget: number }
      - { name: image, label: Image, widget: image }
